# Generated by Django 4.1.3 on 2022-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_transaccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
