export const CURSO_LIST_REQUEST = 'CURSO_LIST_REQUEST'
export const CURSO_LIST_SUCCESS = 'CURSO_LIST_SUCCESS'
export const CURSO_LIST_FAIL = 'CURSO_LIST_FAIL'

export const CURSO_LAST_REQUEST = 'CURSO_LAST_REQUEST'
export const CURSO_LAST_SUCCESS = 'CURSO_LAST_SUCCESS'
export const CURSO_LAST_FAIL = 'CURSO_LAST_FAIL'

export const CURSO_DETAILS_REQUEST = 'CURSO_DETAILS_REQUEST'
export const CURSO_DETAILS_SUCCESS = 'CURSO_DETAILS_SUCCESS'
export const CURSO_DETAILS_FAIL = 'CURSO_DETAILS_FAIL'

export const CURSO_DELETE_REQUEST = 'CURSO_DELETE_REQUEST'
export const CURSO_DELETE_SUCCESS = 'CURSO_DELETE_SUCCESS'
export const CURSO_DELETE_FAIL = 'CURSO_DELETE_FAIL'

export const CURSO_CREATE_REQUEST = 'CURSO_CREATE_REQUEST'
export const CURSO_CREATE_SUCCESS = 'CURSO_CREATE_SUCCESS'
export const CURSO_CREATE_FAIL = 'CURSO_CREATE_FAIL'
export const CURSO_CREATE_RESET = 'CURSO_CREATE_RESET'

export const CURSO_UPDATE_REQUEST = 'CURSO_UPDATE_REQUEST'
export const CURSO_UPDATE_SUCCESS = 'CURSO_UPDATE_SUCCESS'
export const CURSO_UPDATE_FAIL = 'CURSO_UPDATE_FAIL'
export const CURSO_UPDATE_RESET = 'CURSO_UPDATE_RESET'

export const CURSO_CREATE_REVIEW_REQUEST = 'CURSO_CREATE_REVIEW_REQUEST'
export const CURSO_CREATE_REVIEW_SUCCESS = 'CURSO_CREATE_REVIEW_SUCCESS'
export const CURSO_CREATE_REVIEW_FAIL = 'CURSO_CREATE_REVIEW_FAIL'
export const CURSO_CREATE_REVIEW_RESET = 'CURSO_CREATE_REVIEW_RESET'

export const CURSO_CREATE_EPISODIO_REQUEST = 'CURSO_CREATE_EPISODIO_REQUEST';
export const CURSO_CREATE_EPISODIO_SUCCCESS = 'CURSO_CREATE_EPISODIO_SUCCCESS';
export const CURSO_CREATE_EPISODIO_FAIL = 'CURSO_CREATE_EPISODIO_FAIL';
export const CURSO_CREATE_EPISODIO_RESET = 'CURSO_CREATE_EPISODIO_RESET';

export const EPISODIO_UPDATE_REQUEST = 'EPISODIO_UPDATE_REQUEST';
export const EPISODIO_UPDATE_SUCCESS = 'EPISODIO_UPDATE_SUCCESS';
export const EPISODIO_UPDATE_FAIL = 'EPISODIO_UPDATE_FAIL';
export const EPISODIO_UPDATE_RESET = 'EPISODIO_UPDATE_RESET';

export const EPISODIO_DETAILS_REQUEST = 'EPISODIO_DETAILS_REQUEST';
export const EPISODIO_DETAILS_SUCCESS = 'EPISODIO_DETAILS_SUCCESS';
export const EPISODIO_DETAILS_FAIL = 'EPISODIO_DETAILS_FAIL';

export const EPISODIO_CREATE_COMMENT_REQUEST = 'EPISODIO_CREATE_COMMENT_REQUEST'
export const EPISODIO_CREATE_COMMENT_SUCCESS = 'EPISODIO_CREATE_COMMENT_SUCCESS'
export const EPISODIO_CREATE_COMMENT_FAIL = 'EPISODIO_CREATE_COMMENT_FAIL'
export const EPISODIO_CREATE_COMMENT_RESET = 'EPISODIO_CREATE_COMMENT_RESET'

export const EPISODIO_ALL_REQUEST = 'EPISODIO_ALL_REQUEST'
export const EPISODIO_ALL_SUCCESS = 'EPISODIO_ALL_SUCCESS'
export const EPISODIO_ALL_FAIL = 'EPISODIO_ALL_FAIL'

export const EPISODIO_DELETE_REQUEST = 'EPISODIO_DELETE_REQUEST'
export const EPISODIO_DELETE_SUCCESS = 'EPISODIO_DELETE_SUCCESS'
export const EPISODIO_DELETE_FAIL = 'EPISODIO_DELETE_FAIL'






