export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const URL_LIST_REQUEST = 'URL_LIST_REQUEST'
export const URL_LIST_SUCCESS = 'URL_LIST_SUCCESS'
export const URL_LIST_FAIL = 'URL_LIST_FAIL'

export const URL_DELETE_REQUEST = 'URL_DELETE_REQUEST'
export const URL_DELETE_SUCCESS = 'URL_DELETE_SUCCESS'
export const URL_DELETE_FAIL = 'URL_DELETE_FAIL'

export const URL_CREATE_REQUEST = 'URL_CREATE_REQUEST'
export const URL_CREATE_SUCCESS = 'URL_CREATE_SUCCESS'
export const URL_CREATE_FAIL = 'URL_CREATE_FAIL'
export const URL_CREATE_RESET = 'URL_CREATE_RESET'

export const URL_UPDATE_REQUEST = 'URL_UPDATE_REQUEST'
export const URL_UPDATE_SUCCESS = 'URL_UPDATE_SUCCESS'
export const URL_UPDATE_FAIL = 'URL_UPDATE_FAIL'
export const URL_UPDATE_RESET = 'URL_UPDATE_RESET'

export const URL_DETAILS_REQUEST = 'URL_DETAILS_REQUEST'
export const URL_DETAILS_SUCCESS = 'URL_DETAILS_SUCCESS'
export const URL_DETAILS_FAIL = 'URL_DETAILS_FAIL'