# Generated by Django 4.1.3 on 2022-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(blank=True, default='/curso.jpg', null=True, upload_to='cursos/'),
        ),
    ]
