# Generated by Django 3.2 on 2022-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_description_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='video',
        ),
        migrations.AddField(
            model_name='episodio',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
