# Generated by Django 3.2 on 2022-11-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_auto_20221118_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
