# Generated by Django 3.2 on 2022-11-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_trailer_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='trailer_url',
            new_name='trailer',
        ),
    ]
