# Generated by Django 3.2 on 2022-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_remove_episodio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
