# Generated by Django 3.2 on 2022-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_episodio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
