export const CURSO_LIST_REQUEST = 'CURSO_LIST_REQUEST'
export const CURSO_LIST_SUCCESS = 'CURSO_LIST_SUCCESS'
export const CURSO_LIST_FAIL = 'CURSO_LIST_FAIL'

export const CURSO_LAST_REQUEST = 'CURSO_LAST_REQUEST'
export const CURSO_LAST_SUCCESS = 'CURSO_LAST_SUCCESS'
export const CURSO_LAST_FAIL = 'CURSO_LAST_FAIL'

export const CURSO_DETAILS_REQUEST = 'CURSO_DETAILS_REQUEST'
export const CURSO_DETAILS_SUCCESS = 'CURSO_DETAILS_SUCCESS'
export const CURSO_DETAILS_FAIL = 'CURSO_DETAILS_FAIL'

export const CURSO_DELETE_REQUEST = 'CURSO_DELETE_REQUEST'
export const CURSO_DELETE_SUCCESS = 'CURSO_DELETE_SUCCESS'
export const CURSO_DELETE_FAIL = 'CURSO_DELETE_FAIL'

export const CURSO_CREATE_REQUEST = 'CURSO_CREATE_REQUEST'
export const CURSO_CREATE_SUCCESS = 'CURSO_CREATE_SUCCESS'
export const CURSO_CREATE_FAIL = 'CURSO_CREATE_FAIL'
export const CURSO_CREATE_RESET = 'CURSO_CREATE_RESET'

export const CURSO_UPDATE_REQUEST = 'CURSO_UPDATE_REQUEST'
export const CURSO_UPDATE_SUCCESS = 'CURSO_UPDATE_SUCCESS'
export const CURSO_UPDATE_FAIL = 'CURSO_UPDATE_FAIL'
export const CURSO_UPDATE_RESET = 'CURSO_UPDATE_RESET'

export const CURSO_CREATE_REVIEW_REQUEST = 'CURSO_CREATE_REVIEW_REQUEST'
export const CURSO_CREATE_REVIEW_SUCCESS = 'CURSO_CREATE_REVIEW_SUCCESS'
export const CURSO_CREATE_REVIEW_FAIL = 'CURSO_CREATE_REVIEW_FAIL'
export const CURSO_CREATE_REVIEW_RESET = 'CURSO_CREATE_REVIEW_RESET'


