# Generated by Django 4.1.3 on 2022-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.jpg', null=True, upload_to='users/'),
        ),
    ]
