# Generated by Django 4.1.3 on 2022-11-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.jpg', null=True, upload_to='users'),
        ),
    ]
